version: '3.8'

x-service: &service
  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "2"
  restart: "on-failure"

services:

  minio:
    <<: *service
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: sh
    command: -c 'mkdir -p /data/clickhouse && /usr/bin/minio server --address :9000 --console-address :9001 /data'
    ports:
      - 9001:9001
    volumes:
      - ./data/minio:/data

  clickhouse:
    <<: *service
    image: bitnami/clickhouse:23
    environment:
      CLICKHOUSE_ADMIN_PASSWORD: default
      CLICKHOUSE_MOUNTED_DIR: /bitnami/clickhouse
    ports:
      - 9000:9000
      - 9004:9004
      - 9005:9005
      - 8123:8123
    volumes:
      - ./configs/clickhouse/:/bitnami/clickhouse/etc/conf.d/
      #- ./data/clickhouse:/bitnami/clickhouse

  postgres:
    <<: *service
    image: postgres:alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    ports:
      - 5432:5432
    #volumes:
      #- ./data/postgres:/var/lib/postgresql/data

  mailhog:
    <<: *service
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  uptrace:
    <<: *service
    image: uptrace/uptrace
    ports:
      - 14317:14317
      - 14318:14318
    volumes:
      - ./configs/uptrace/uptrace.yml:/etc/uptrace/uptrace.yml

  grafana:
    <<: *service
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana:/etc/grafana/provisioning

  telegraf:
    <<: *service
    image: telegraf
    volumes:
      - ./configs/telegraf:/etc/telegraf
