apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://uptrace:14318/api/prometheus
    editable: true
    jsonData:
      httpHeaderName1: 'uptrace-dsn'
    secureJsonData:
      httpHeaderValue1: 'http://project2_secret_token@localhost:14317/2'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://uptrace:14318/api/tempo
    editable: true
    jsonData:
      httpHeaderName1: 'uptrace-dsn'
    secureJsonData:
      httpHeaderValue1: 'http://project2_secret_token@localhost:14317/2'

  - name: Uptrace Tempo
    type: tempo
    access: proxy
    url: http://uptrace:14318/api/tempo
    editable: true
    jsonData:
      httpHeaderName1: 'uptrace-dsn'
    secureJsonData:
      httpHeaderValue1: 'http://project1_secret_token@localhost:14317/1'

  - name: Uptrace Prometheus
    type: prometheus
    access: proxy
    url: http://uptrace:14318/api/prometheus
    editable: true
    jsonData:
      httpHeaderName1: 'uptrace-dsn'
    secureJsonData:
      httpHeaderValue1: 'http://project1_secret_token@localhost:14317/1'
